spring:
  security:
    user:
      name: user
      password: 1
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/notarizemvc
    username: postgres
    password: 6270
    driverClassName: org.postgresql.Driver
  #    data: 'classpath:data.sql'
  #    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: true
#  batch:
#    initialize-schema: always
server:
  port: 80